### ISSUE TITLE
Doctor profile

### ISSUE THREAD

**Issue by prokov00** [Ascendancey/brunette-humming-birds#11]
As a user, I want to get all the crucial information from a quick glance so that I can find a good doctor quickly.

Each doctor should consist of 

- [x] Name + title
- [x] Profile picture
- [ ] Is it available now? (maybe an icon)
- [x] Specialization
- "Rating" component
- [x] Info button (This button takes you to the detail page see next story)
- [x] Location

**Comment by Ascendancey** [comment]
@ZOOTAA rating component and availability left

**Comment by Ascendancey** [comment]
Implemented
