### ISSUE TITLE
Booking pop-up

### ISSUE THREAD

**Issue by MujtabaMukhtar** [Ascendancey/brunette-humming-birds#4]
As a user, I want to be able to click on an available time slot and book it. I also want to give the doctor a little bit of information so he can maybe prepare for our video call. 

Acceptance criteria:

- [x] The user can click on available time slots on the calendar and a pop-up will open with the following fields:
- [x] Date and time of the appointment (take the date from the booked slot in the story before)
- [x] Choose the type of appointment (video call, physical, audio call…)
- [x] Description field which the patient can fill to give a little bit of prior information 
- [x] Book now button
- [x] Cancel button

- [x] Once the user clicks “Book now” the pop-up is closed and the newly booked appointment is shown in the calendar (not shown but could be greyed out or some other visual cue)

- [x] Pass the booking values to main App State

**Comment by Ascendancey** [comment]
@ZOOTAA could you please prepare an object to be exported from this to main App State

**Comment by Ascendancey** [comment]
Implemented
