### ISSUE TITLE
Ranking list

### ISSUE THREAD

**Issue by prokov00** [Ascendancey/brunette-humming-birds#9]
As a user once I searched for a doctor I want to see a list of all the doctors that fit those criteria ordered by rank, next to that I would like to see some crucial information on the doctors so I can make an easier decision on which to pick. 

Acceptance criteria:

- [x] Create a list view that shows a definitive (e.g. 10) number of "Doctor profile" components
- [x] The "Doctor profile components" are sorted by rank by default
- [ ] On the bottom of the page, you have pagination controls if there are more than 10 doctors for example
- [x] Add the "Search bar" component on top of the page

**Comment by Ascendancey** [comment]
Implemented
